services:
  - type: web
    name: futuristai
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    branch: main
    region: oregon
    rootDir: .